export const LOGICAL_WIDTH = 960;
export const LOGICAL_HEIGHT = 540;
export const FIXED_STEP_SECONDS = 1 / 60;
export const MAX_STEPS_PER_FRAME = 5;
export const MAX_DEVICE_PIXEL_RATIO = 2;
export const STATE = Object.freeze({
  MENU: "MENÚ",
  PLAYING: "JUGANDO",
  PAUSED: "PAUSA",
  GAME_OVER: "GAME OVER",
  SELECT_FIGHTER: "SELECCIÓN",
  LEVEL_INTRO: "INTRO NIVEL",
  VICTORY: "VICTORIA",
  HOW_TO_PLAY: "CÓMO JUGAR",
  ARCHIVE: "ARCHIVO",
  LEVEL_CLEAR: "RESULTADO",
});
